name: RenYuan-Core
version: '${project.version}'
main: ren.rymc.renyuancore.RenYuanCore
softdepend:
  - floodgate
  - Multiverse-Core
  - QuickShop
  - Essentials
  - CMI
  - Residence
  - ViaVersion
api-version: 1.17
authors:
  - RENaa_FD
website: https://rymc.ren/
description: "任渊生存服务端功能核心插件"
commands:
  spawn:
    description: "回主城"
    usage: ""
  setspawn:
    description: "设置主城"
    usage: ""
  renyuancore:
    description: "任渊功能插件相关指令"
    usage: ""
  loadpack:
    description: "加载资源包"
    usage: ""
  obemenu:
    description: "基岩版菜单"
    usage: ""
permissions:
  spawn.build:
    description: "主城建筑权限"
    default: op
  spawn.set:
    description: "主城设置权限"
    default: op
  renyuancore.admin:
    description: "任渊生存功能核心的主权限"
    default: op